package:
  name: rhealpixdggs
  version: 0.5.6

source:
  url: https://github.com/manaakiwhenua/rhealpixdggs-py/archive/refs/heads/conda-package.zip
  sha256: e3e23a9a02d294fd5d85c7f24c1e29ed4713b9103dd925e196bdc209734e5a1a

build:
  noarch: python
  script: pip install .
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.11
    - numpy >=1.25.2
    - scipy >=1.11.2
    - matplotlib-base >=3.7.2
    - pyproj >=3.6.1
    - shapely >=2.0.1

tests:
  - python:
      imports:
        - rhealpixdggs
      pip_check: true
    ## Could add internal tests if these were included in the package
    ### - python -m unittest discover ../tests/ 
    ### - python -m doctest ../docs/source/introduction.rst ../rhealpixdggs/*.py

about:
  ### homepage: "https://datastore.landcareresearch.co.nz/dataset/rhealpix-discrete-global-grid-system"
  repository: "https://github.com/manaakiwhenua/rhealpixdggs-py"
  summary: An implementation of the rHEALPix discrete global grid system
  license: GPL-3.0-or-later
  license_file: LICENSE

### extra:
  ### recipe-maintainers:
    ### - name_of_maintainer
