package:
  name: rhealpixdggs
  version: 0.5.8

source:
  url: https://pypi.io/packages/source/r/rhealpixdggs/rhealpixdggs-0.5.8.tar.gz
  sha256: c2dc5c250b16d8681bb6ae24800296ea4c73286b1215123ba76311818cc70049

build:
  noarch: python
  script: pip install .
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.11
    - numpy >=2.0
    - scipy >=1.11
    - matplotlib-base >=3.7
    - pyproj >=3.6
    - shapely >=2.1

tests:
  - python:
      imports:
        - rhealpixdggs
      pip_check: true
  - script:
      - python -m unittest discover tests/
      - python -m doctest docs/source/introduction.rst
      - python -m doctest rhealpixdggs/*.py
    files:
      source:
        - tests/
        - docs/
        - rhealpixdggs/

about:
  ### homepage: "https://datastore.landcareresearch.co.nz/dataset/rhealpix-discrete-global-grid-system"
  repository: "https://github.com/manaakiwhenua/rhealpixdggs-py"
  summary: An implementation of the rHEALPix discrete global grid system
  ## license is taken from python source anyway regardless of license
  ## and license_file, leaving these details out here avoids a warning
  ### license: GPL-3.0-or-later
  ### license_file: LICENSE

extra:
  recipe-maintainers:
    - alpha-beta-soup
  tags:
    - rhealpix
    - DGGS
    - Discrete Global Grid System
    - geospatial
    - spatial
    - reference system
