package:
  name: rhealpixdggs
  version: 0.5.6

source:
  url: file://PYTHON_DIST_DIR
  sha256: PYTHON_DIST_SHA26

build:
  noarch: python
  ### script: pip install . -vv --no-deps --no-build-isolation
  script: pip install .
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.11
    - numpy >=1.25.2
    - scipy >=1.11.2
    - matplotlib-base >=3.7.2
    - pyproj >=3.6.1
    - shapely >=2.0.1

### test:
  ### imports:
    ### - rhealpixdggs
  ### commands:
    ### - pip check
  ### requires:
    ### - pip

about:
  summary: An implementation of the rHEALPix discrete global grid system
  license: LGPL-3.0-only
  license_file: LICENSE

### extra:
  ### recipe-maintainers:
    ### - aheays
